### ISSUE TITLE
v1.2.0 execution broken

### ISSUE THREAD

**Issue by AndreasGocht** [tud-zih-energy/voice-annotation-tool#1]
Hey,

there seems to be a build or execution error, at least on Windows machines:

```
(python3.9) PS C:\some\path> voice-annotation-tool.exe
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\some\path\venv\python3.9\Scripts\voice-annotation-tool.exe\__main__.py", line 4, in <module>
  File "C:\some\path\venv\python3.9\lib\site-packages\annotation_tool\main.py", line 11, in <module>
    from .opened_project_frame import OpenedProjectFrame
  File "C:\some\path\venv\python3.9\lib\site-packages\annotation_tool\opened_project_frame.py", line 14, in <module>
    from .loading_dialog import LoadingDialog
ImportError: cannot import name 'LoadingDialog' from 'annotation_tool.loading_dialog' (C:\some\path\venv\python3.9\lib\site-packages\annotation_tool\loading_dialog.py)
```

Installed via:

```
git clone git@github.com:tud-zih-energy/voice-annotation-tool.git
cd voice-annotation-tool
pip install .
```

Best,

Andreas

**Comment by FeliksWeber** [comment]
I squashed and pushed a development branch. I force-pushed the latest working version.
