### ISSUE TITLE
Windows Missing Audio Symbols

### ISSUE THREAD

**Issue by AndreasGocht** [tud-zih-energy/voice-annotation-tool#2]
Using Windows the Audiosymbols like play and pause are missing (see the Picture below).

![Screenshot 2022-02-10 200253](https://user-images.githubusercontent.com/4275850/153478721-4015031c-ff8d-4545-974f-7f71631e8333.png)

Best,

Andreas

**Comment by FeliksWeber** [comment]
I can't reproduce this issue. Can you try uninstalling with
`pip3 uninstall voice-annotation-tool-feliks-weber` and installing again?
This probably has to do with resource files being missing. Can you verify that it was generated and saved to `src/annotation_tool/resources_rc.py`?

**Comment by AndreasGocht** [comment]
Hey,

now it crashes with the following message ;-) : 

```
(python3.9) PS C:\Users\Gocht\Documents\code\voice-annotation-tool> voice-annotation-tool.exe
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Gocht\Documents\code\virtenv\python3.9\Scripts\voice-annotation-tool.exe\__main__.py", line 7, in <module>
  File "C:\Users\Gocht\Documents\code\virtenv\python3.9\lib\site-packages\annotation_tool\main.py", line 9, in main
    app = Application(sys.argv)
  File "C:\Users\Gocht\Documents\code\virtenv\python3.9\lib\site-packages\annotation_tool\application.py", line 41, in __init__
    main_window.load_settings(get_settings_file())
  File "C:\Users\Gocht\Documents\code\virtenv\python3.9\lib\site-packages\annotation_tool\main_window.py", line 84, in load_settings
    self.opened_project_frame.apply_shortcuts(self.shortcuts)
  File "C:\Users\Gocht\Documents\code\virtenv\python3.9\lib\site-packages\annotation_tool\opened_project_frame.py", line 78, in apply_shortcuts
    button = self.playback_buttons[buttonNum]
IndexError: list index out of range
```

But this might be due to a git pull to the latest version ^^.

Best,

Andreas

**Comment by AndreasGocht** [comment]
fixed with #8

**Comment by AndreasGocht** [comment]
However, the Icons still seem to be missing. Let's discuss this later in a call.

Best,

Andreas

**Comment by FeliksWeber** [comment]
I can't reproduce this on a clean virtual machine. There are two things that would be helpful:
Showing the output of running `pytest`.
Testing out the `use-pngs` branch to see if the error is related to svg rendering.
